server:
  port: 8080

spring:
    datasource:
        name: mydata
        url: jdbc:mysql://127.0.0.1:3306/mydata?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名（数据库d_id匹配实体类dId）
logging:
  level:
    cn.zyzpp.xxxx.mapper: debug #打印SQL日志